name: Walking On
author: 空中的风景
markdown: redcarpet
pygments: true
description: 一阶一景，路漫漫
baseurl:http://hejun-lyne.github.io
github: http://www.github.com/hejun-lyne
diandian: http://hejun-lyne.diandian.com/
email: hejun.lyne[at]gmail.com.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

